//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.03 at 12:36:58 PM ICT 
//


package com.akiradata.orca.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.akiradata.orca.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ContentType_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "content-type");
    private final static QName _Segments_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "segments");
    private final static QName _Content_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "content");
    private final static QName _Items_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "items");
    private final static QName _Item_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "item");
    private final static QName _ContentCache_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "content-cache");
    private final static QName _ContentLength_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "content-length");
    private final static QName _Segment_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "segment");
    private final static QName _OrcaProject_QNAME = new QName("http://www.akirdata.com/orca/orca-project", "orca-project");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.akiradata.orca.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SegmentType }
     * 
     */
    public SegmentType createSegmentType() {
        return new SegmentType();
    }

    /**
     * Create an instance of {@link ItemType }
     * 
     */
    public ItemType createItemType() {
        return new ItemType();
    }

    /**
     * Create an instance of {@link OrcaProjectType }
     * 
     */
    public OrcaProjectType createOrcaProjectType() {
        return new OrcaProjectType();
    }

    /**
     * Create an instance of {@link ItemListType }
     * 
     */
    public ItemListType createItemListType() {
        return new ItemListType();
    }

    /**
     * Create an instance of {@link SegmentListType }
     * 
     */
    public SegmentListType createSegmentListType() {
        return new SegmentListType();
    }

    /**
     * Create an instance of {@link SegmentType.Bound }
     * 
     */
    public SegmentType.Bound createSegmentTypeBound() {
        return new SegmentType.Bound();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "content-type")
    public JAXBElement<String> createContentType(String value) {
        return new JAXBElement<String>(_ContentType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SegmentListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "segments")
    public JAXBElement<SegmentListType> createSegments(SegmentListType value) {
        return new JAXBElement<SegmentListType>(_Segments_QNAME, SegmentListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "content")
    public JAXBElement<byte[]> createContent(byte[] value) {
        return new JAXBElement<byte[]>(_Content_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "items")
    public JAXBElement<ItemListType> createItems(ItemListType value) {
        return new JAXBElement<ItemListType>(_Items_QNAME, ItemListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "item")
    public JAXBElement<ItemType> createItem(ItemType value) {
        return new JAXBElement<ItemType>(_Item_QNAME, ItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "content-cache")
    public JAXBElement<String> createContentCache(String value) {
        return new JAXBElement<String>(_ContentCache_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "content-length")
    public JAXBElement<Integer> createContentLength(Integer value) {
        return new JAXBElement<Integer>(_ContentLength_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "segment")
    public JAXBElement<SegmentType> createSegment(SegmentType value) {
        return new JAXBElement<SegmentType>(_Segment_QNAME, SegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrcaProjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.akirdata.com/orca/orca-project", name = "orca-project")
    public JAXBElement<OrcaProjectType> createOrcaProject(OrcaProjectType value) {
        return new JAXBElement<OrcaProjectType>(_OrcaProject_QNAME, OrcaProjectType.class, null, value);
    }

}
