//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.03 at 12:36:58 PM ICT 
//


package com.akiradata.orca.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for segment-type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="segment-type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="bound">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="x1" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="y1" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="x2" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                 &lt;attribute name="y2" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="colour" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accessible-content">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="accessile-content-type">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="label" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "segment-type", propOrder = {
    "bound",
    "colour",
    "accessibleContent",
    "accessileContentType"
})
public class SegmentType {

    @XmlElement(required = true)
    protected SegmentType.Bound bound;
    protected String colour;
    @XmlElement(name = "accessible-content", required = true)
    protected String accessibleContent;
    @XmlElement(name = "accessile-content-type", required = true)
    protected String accessileContentType;
    @XmlAttribute(name = "id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;
    @XmlAttribute(name = "label")
    protected String label;

    /**
     * Gets the value of the bound property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentType.Bound }
     *     
     */
    public SegmentType.Bound getBound() {
        return bound;
    }

    /**
     * Sets the value of the bound property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentType.Bound }
     *     
     */
    public void setBound(SegmentType.Bound value) {
        this.bound = value;
    }

    /**
     * Gets the value of the colour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColour() {
        return colour;
    }

    /**
     * Sets the value of the colour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColour(String value) {
        this.colour = value;
    }

    /**
     * Gets the value of the accessibleContent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessibleContent() {
        return accessibleContent;
    }

    /**
     * Sets the value of the accessibleContent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessibleContent(String value) {
        this.accessibleContent = value;
    }

    /**
     * Gets the value of the accessileContentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessileContentType() {
        return accessileContentType;
    }

    /**
     * Sets the value of the accessileContentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessileContentType(String value) {
        this.accessileContentType = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the label property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLabel() {
        return label;
    }

    /**
     * Sets the value of the label property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLabel(String value) {
        this.label = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="x1" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="y1" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="x2" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *       &lt;attribute name="y2" use="required" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Bound {

        @XmlAttribute(name = "x1", required = true)
        protected double x1;
        @XmlAttribute(name = "y1", required = true)
        protected double y1;
        @XmlAttribute(name = "x2", required = true)
        protected double x2;
        @XmlAttribute(name = "y2", required = true)
        protected double y2;

        /**
         * Gets the value of the x1 property.
         * 
         */
        public double getX1() {
            return x1;
        }

        /**
         * Sets the value of the x1 property.
         * 
         */
        public void setX1(double value) {
            this.x1 = value;
        }

        /**
         * Gets the value of the y1 property.
         * 
         */
        public double getY1() {
            return y1;
        }

        /**
         * Sets the value of the y1 property.
         * 
         */
        public void setY1(double value) {
            this.y1 = value;
        }

        /**
         * Gets the value of the x2 property.
         * 
         */
        public double getX2() {
            return x2;
        }

        /**
         * Sets the value of the x2 property.
         * 
         */
        public void setX2(double value) {
            this.x2 = value;
        }

        /**
         * Gets the value of the y2 property.
         * 
         */
        public double getY2() {
            return y2;
        }

        /**
         * Sets the value of the y2 property.
         * 
         */
        public void setY2(double value) {
            this.y2 = value;
        }

    }

}
